In [1]:
import torch
from torch import nn

In [3]:
a = torch.tensor([[1,0],[0,1]])

In [4]:
a

tensor([[1, 0],
        [0, 1]])

In [5]:
a.eq(0)

tensor([[0, 1],
        [1, 0]], dtype=torch.uint8)

In [11]:
a = torch.rand(2, 3, 3)

In [14]:
a.data.new(a.size(1)).zers_()

AttributeError: 'Tensor' object has no attribute 'zers_'

In [12]:
a

tensor([[[0.6091, 0.4653, 0.7765],
         [0.3673, 0.5402, 0.0176],
         [0.5671, 0.7704, 0.1754]],

        [[0.7667, 0.5226, 0.5355],
         [0.7320, 0.0618, 0.5223],
         [0.4244, 0.3871, 0.7848]]])